# Generated by Django 3.1.1 on 2021-07-06 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keyword_Name', models.CharField(max_length=100)),
                ('search_volums', models.FloatField()),
                ('Trend', models.IntegerField()),
                ('cpc', models.IntegerField()),
                ('competition', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
