# Generated by Django 3.1.1 on 2021-07-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_sslist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sslist',
            old_name='Keyword_Name',
            new_name='keyword_name',
        ),
        migrations.AlterField(
            model_name='sslist',
            name='competition',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sslist',
            name='cpc',
            field=models.FloatField(),
        ),
    ]
