# Generated by Django 3.1.1 on 2021-07-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210706_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslist',
            name='search_volums',
            field=models.IntegerField(),
        ),
    ]
