# Generated by Django 3.1.1 on 2021-07-09 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20210706_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sslist',
            name='user',
        ),
        migrations.AddField(
            model_name='sslist',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
