# Generated by Django 3.1.1 on 2021-07-14 03:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20210709_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslist',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SSListUser',
        ),
    ]
