# Generated by Django 3.1.1 on 2021-07-14 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210714_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sslist',
            old_name='user',
            new_name='user1',
        ),
    ]
