# Generated by Django 3.1.1 on 2021-07-31 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_auto_20210714_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupSubmissionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('site', models.CharField(blank=True, max_length=256, null=True)),
                ('site_type', models.CharField(blank=True, max_length=256, null=True)),
                ('da_score', models.IntegerField(default=0)),
                ('monthly_traffic', models.IntegerField(default=0)),
                ('follow_unfollow_link', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ManyToManyField(blank=True, related_name='user_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Startup Submission List',
            },
        ),
        migrations.DeleteModel(
            name='SSList',
        ),
    ]
